### ISSUE TITLE
Capacitor

### ISSUE THREAD

**Issue by GraT3004** [jbhv03/jbhv03.github.io#1]
I am interested by using openjdk, gradle and android sdk, and compile html/js applications with capacitor but I can't see any link in your bio so I leave you a message here. Please send me a message to my electronic address: lglglg3004@gmail.com . I look for you help    @jbhv03

**Comment by jbhv03** [comment]
I have sent you an email

**Comment by GraT3004** [comment]
Hello !  Thanks for sending me a mail. Now I want to ask to you how to make
an Android application with capacitor on termux.

**Comment by GraT3004** [comment]
Using html and js

**Comment by jbhv03** [comment]
I sent you in my mail different ways to contact me outside github, so we can exchange more easily. Can you please use them.
